### ISSUE TITLE
Tidy Up Badges Situation in this Repo

### ISSUE THREAD

**Issue by nelsonic** [dwyl/learn-tape#14]
Currently, the badges are not displaying correctly ...
https://github.com/dwyl/learn-tape/tree/4ec8694364f579d1fac225fb874dc7a87c804c1f
![image](https://cloud.githubusercontent.com/assets/194400/25842813/39084938-349d-11e7-9ff3-03696e45470d.png)

This shouldn't take long to fix if someone has time ... please/thanks! ❤️ ✅

**Comment by nelsonic** [comment]
Getting:
![image](https://cloud.githubusercontent.com/assets/194400/25902266/0211e6e2-3591-11e7-93d1-2f67d673b511.png)
investigating _why_...!

**Comment by nelsonic** [comment]
CodeCov Badge still not working ... [![codecov](https://codecov.io/gh/dwyl/learn-tape/branch/tape/graph/badge.svg)](https://codecov.io/gh/dwyl/learn-tape) 😞

**Comment by emersonmellado** [comment]
PR #24 out!

**Comment by nelsonic** [comment]
Confirmed: [![codecov](https://codecov.io/gh/dwyl/learn-tape/branch/master/graph/badge.svg)](https://codecov.io/gh/dwyl/learn-tape/branch/master)
Thanks @emersonmellado 👍

**Comment by nelsonic** [comment]
Code Climate is complaining about "_similar code_" in our _tests_ ... [![Code Climate](https://codeclimate.com/github/dwyl/learn-tape.png)](https://codeclimate.com/github/dwyl/learn-tape)

see: https://codeclimate.com/github/dwyl/learn-tape/front-end-testing/test-complete/test.spec.js
We need to _either_ setup a file to _ignore_ the `/test` directory _or_ comment out the badge.
