### ISSUE TITLE
Add "Testing front end code with tape" file

### ISSUE THREAD

**Issue by ZooeyMiller** [dwyl/learn-tape#17]
As detailed in https://github.com/dwyl/learn-offline-first/issues/11 we (@finnhodgkin and I) would like to take our learnings about using JSDOM and tape to test front end code (that we gained whilst working on [`learn-offline-first`](https://github.com/dwyl/learn-offline-first)) and make a separate .md file in this repo that will be linked at the bottom of the README.md.

**Comment by nelsonic** [comment]
@ZooeyMiller you should be good to go.
![image](https://user-images.githubusercontent.com/194400/27578945-a9b92a34-5b1d-11e7-9c5a-bc081ebd7839.png)
If you have any questions, ask! 🎉

**Comment by ZooeyMiller** [comment]
@nelsonic Whilst Finn is busy with doing stuff for his week at Founders and Coders I am going to work on this (at least for the morning).

**Comment by nelsonic** [comment]
@ZooeyMiller good plan. 👍

**Comment by ZooeyMiller** [comment]
4hr time estimate was inaccurate due to external circumstances, overall I think this is 4hrs of **actual** work, just not 4hrs in real time.

**Comment by nelsonic** [comment]
@ZooeyMiller thanks for updating. 👍 
PR is looking good. please assign when you think it's ready for review. 😉
