### ISSUE TITLE
Write an example of some front end code to test with tape

### ISSUE THREAD

**Issue by ZooeyMiller** [dwyl/learn-tape#18]
For #17 I need to make an example of some front end code to test with Tape to write the .md file on how to do it. 

I am planning on making a basic increment/decrement/reset counter

**Comment by ZooeyMiller** [comment]
@nelsonic is it okay to take the css from https://github.com/dwyl/learn-elm-architecture-in-javascript ?

(I'm going to write my own script file so that it's a little more simple than learn-elm-architecture-in-javascript)

**Comment by ZooeyMiller** [comment]
Fixed by 78ffd68, will close this issue when it's merged into master

**Comment by nelsonic** [comment]
@ZooeyMiller yes, please "_re-cycle_" wherever possible to reduce work. ♻️  👍 

also, I would _really_ appreciate a question/issue on https://github.com/dwyl/learn-elm-architecture-in-javascript so we can _clarify_ why some people feel it's not "_simple_" ... ❓ 😕  (_thanks!_)

**Comment by ZooeyMiller** [comment]
@nelsonic Thanks, that's ace. Will try to have a read through with someone who found it difficult and raise an issue.
