### ISSUE TITLE
Update Tape tests from tap.createConsumer to concat-stream

### ISSUE THREAD

**Issue by nelsonic** [dwyl/learn-tape#2]
While reading Tape source code I decided to check the devDependendices and spotted that they are _way_ out-of-date: https://github.com/substack/tape/issues/312

When we update devDependencies 25 tests fail.
<img width="498" alt="tape-test-fail" src="https://cloud.githubusercontent.com/assets/194400/18030667/934c58ee-6cb6-11e6-9a54-29b0192359c4.png">

This is because `tap` no longer has a `createConsumer` method.

After a bit of googling we found a "_guide_" for how to update the tests...
See: https://github.com/substack/tape/pull/171/files

**Comment by nelsonic** [comment]
Run an individual `tap` test with:

``` sh
node_modules/.bin/tap test/array.js
```

<img width="475" alt="tap-run-one-test" src="https://cloud.githubusercontent.com/assets/194400/18030678/4657bb9a-6cb7-11e6-8a90-b1c4437dda0c.png">

**Comment by nelsonic** [comment]
Once we update the `test/array.js` to use `concat-stream` the test passes:
<img width="473" alt="tape-array-test-passes-after-update" src="https://cloud.githubusercontent.com/assets/194400/18031035/2e8cd3a6-6cc6-11e6-8f6f-9bd1ce80efac.png">

**Comment by nelsonic** [comment]
Once we update the `test/array.js` it passes:
<img width="473" alt="tape-array-test-passes-after-update" src="https://cloud.githubusercontent.com/assets/194400/18031228/2db12808-6cce-11e6-9669-083d4443a0f5.png">

**Comment by nelsonic** [comment]
(Un)_fortunately_ the latest version of `tap` has more _detailed_ **_stack trace**_ when a test fails:

<img width="690" alt="tape-end-as-callaback-error-stacktrace" src="https://cloud.githubusercontent.com/assets/194400/18031315/0b361f36-6cd3-11e6-875c-e6c3349096e0.png">

So in order to make the tests _pass_ we need to _hard code_ the stack trace ...? 😕

**Comment by ghost** [comment]
@nelsonic What is the difference? The path? 
I guess you are testing actual error message wich will be different from computer to computer and even in a CI environment.

I think I had similar issue couple of days ago when I made my own long stack trace solution. One solution I used was `cwd()` and then I also used `indexOf` to do a deep comparison with some of the error message  that I would know was identical and didn't include the paths.  

I further "hacked" into the reporter itself and checked if "failed" was triggered. 

Maybe not the way to go... How is the TAP stack trace code?

**Comment by nelsonic** [comment]
I _initially_ considered writing a function that _attempted_ to return a semi-hard-coded version of the stack trace: 

``` js
var basepath = __filename.replace('test/end-as-callback.js', '');
// stack trace for new tap error 
var s = '  ---\n';
s += '    operator: error\n';
s += '    expected: |-\n';
s += '      undefined\n';
s += '    actual: |-\n';
s += '      [Error: fail]\n';
s += '    stack: |-\n';
s += '      Error: fail\n';
s += '          at fakeAsyncWriteFail (' + basepath + 'test/end-as-callback.js:61:8)\n';
s += '          at ' + basepath + 'test/end-as-callback.js:47:13\n';
s += '          at fakeAsyncTask (' + basepath + 'test/end-as-callback.js:52:5)\n';
s += '          at Test.<anonymous> (' + basepath + 'test/end-as-callback.js:42:9)\n';
s += '          at Test.bound [as _cb] (' + basepath + 'lib/test.js:63:32)\n';
s += '          at Test.run (' + basepath + 'lib/test.js:82:10)\n';
s += '          at Test.bound [as run] (' + basepath + 'lib/test.js:63:32)\n';
s += '          at Immediate.next [as _onImmediate] (' + basepath + 'lib/results.js:71:15)\n';
s += '          at processImmediate [as _immediateCallback] (timers.js:383:17)\n';
s += '  ...\n';
```

But I don't want _everyone_ to hate me each time one of the files gets updated so instead decided to _read_ the stacktrace lines from the `stdout`

**Comment by nelsonic** [comment]
Finished the little `getStackTrace` function. It _should_ be working ... but instead we get:
<img width="685" alt="tape-end-as-callback-should-pass" src="https://cloud.githubusercontent.com/assets/194400/18031644/cfd20fa8-6ce2-11e6-807f-14910fdb2899.png">

What does this mean?!?

``` diff
+++ found
--- wanted
```

There's no difference!

**Comment by nelsonic** [comment]
Tape skip tests are not cooperating ... 
<img width="521" alt="tape-skip-test-failing" src="https://cloud.githubusercontent.com/assets/194400/18034249/fd3ceb28-6d2f-11e6-9b19-2103b56ee168.png">

**Comment by nelsonic** [comment]
When I _attempt_ to re-organise the file I get:
<img width="667" alt="tape-skip-useless" src="https://cloud.githubusercontent.com/assets/194400/18034374/f24b6778-6d32-11e6-8e6b-47cedacc44f9.png">

Which is _worse_ than useless! :-(

**Comment by nelsonic** [comment]
tape `test/throws.js` tests fail inexplicably:
<img width="528" alt="tape-throws-tests-fail-inexplicably" src="https://cloud.githubusercontent.com/assets/194400/18034924/164cef02-6d42-11e6-9f67-d3d43742ef7f.png">

**Comment by nelsonic** [comment]
double-blank-lines in `test/exit.js`
<img width="695" alt="tape-test-exit-double-blank-lines" src="https://cloud.githubusercontent.com/assets/194400/18049224/cd648b22-6dde-11e6-9c6e-e6a66a3a711f.png">

**Comment by nelsonic** [comment]
closing. https://github.com/substack/tape/pull/318 was merged. ✅
