### ISSUE TITLE
Fix repo description

### ISSUE THREAD

**Issue by carloslfu** [dwyl/learn-tape#25]
`Learn how to use Tape for JavaScript/Node.js Test Driven Development (TDD) - Ten-Minute Testing Tuturial` should be `Learn how to use Tape for JavaScript/Node.js Test Driven Development (TDD) - Ten-Minute Testing Tutorial`

**Comment by iteles** [comment]
Ah, thanks for catching that @carloslfu ! 
Should take 2 mins to change.

**Comment by iteles** [comment]
Done! Thanks @carloslfu
