### ISSUE TITLE
Update instances of var to let/const

### ISSUE THREAD

**Issue by victoria-kaihe** [dwyl/learn-tape#27]
README and code could be updated to be in line with ES6+ use of let/const instead of var.

**Comment by iteles** [comment]
@victoria-kaihe Thanks for opening this issue! 🎉 
This is a great suggestion.

If you have some time to put in a PR to update this, it would be very welcome!

**Comment by victoria-kaihe** [comment]
I've cloned down the repo and checked out to a new branch to do the update. I'm having a quick look through now to get an estimate at how long it'll take. Once I've got a timeframe I'll open up a PR and get stuck in!

**Comment by victoria-kaihe** [comment]
I'm thinking a couple of hours, maybe three? Opening up a PR now :)

**Comment by nelsonic** [comment]
Resolved. Closing. Thanks! ✨
