### ISSUE TITLE
Using Tap for Browser Tests 

### ISSUE THREAD

**Issue by nelsonic** [dwyl/learn-tape#6]
Need help adding a section for using Tap for Browser Tests ...
https://gist.github.com/substack/7480813

As a developer, I need to run tests both on the server and client.
Instead of needing _multiple_ testing libraries, I would prefer to use one _everywhere_; tape.
So that I don't waste any time context switching.

**Comment by nelsonic** [comment]
tried to follow Substack's gist and got to this:
![learn-tape-browserify](https://cloud.githubusercontent.com/assets/194400/19897706/0c7e94d4-a051-11e6-94bf-6af464b7cea6.png)

**Comment by jackcarlisle** [comment]
<img width="527" alt="screen shot 2016-11-01 at 16 44 21" src="https://cloud.githubusercontent.com/assets/12450298/19898078/79f41d30-a052-11e6-954b-8dad5fa71771.png">

**Comment by nelsonic** [comment]
when I attempted to run `browserify test/*.js | testling`
I got the error: `No headless browser found.`
Which apparently several other people see: https://github.com/substack/testling/issues/108#issuecomment-250864273

So I did:

```
npm install phantomjs -g
mv ~/.config/browser-launcher/config.json ~/.config/browser-launcher/config.json_bak
```

Now when I run `browserify test/*.js | testling` it totes works.
![learn-tape-testling-passes](https://cloud.githubusercontent.com/assets/194400/19898487/1b47e3aa-a054-11e6-97b4-5d49155f7e64.png)

**Comment by jackcarlisle** [comment]
<img width="660" alt="screen shot 2016-11-01 at 16 57 48" src="https://cloud.githubusercontent.com/assets/12450298/19898553/63e0e8a0-a054-11e6-93e1-2fe4872989ed.png">

**Comment by nelsonic** [comment]
`#ScreenShotPingPong` 😜

**Comment by jackcarlisle** [comment]
🏓💥

**Comment by nelsonic** [comment]
Extensive example: https://github.com/dwyl/todo-list-javascript-tutorial 🚀 
Closing.
